// app/write/page.tsx
"use client";
import Head from "next/head";
import Image from "next/image";
import Search from "../components/Search";
import { cities as citiesArr, departments as deptsArr } from "../lib/utils";
import { useState } from "react";
import SearchAsync from "../components/SearchAsync";
import supabase from "../lib/supabase";

export default function Write() {
    let [error, setError] = useState<string|null>(null);

    function showError(s: string|null) {
        setError(s);
        s && setTimeout(() => setError(null), 5000);
    }
    
    let [dept, setDept] = useState<string[]>([]);
    let [city, setCity] = useState<string[]>([]);
    let [date, setDate] = useState<string>();
    let [title, setTitle] = useState<string>("");
    let [content, setContent] = useState<string>("");
    let [accountable, setAccountable] = useState<ProfileSchema|null>(null);

    async function getData(q: string) {
        return await supabase
            .from("profiles")
            .select("id, name")
            .ilike("name", `%${q}%`)
            .returns<ProfileSchema[]>()
            .limit(20);
    }

    async function handleSubmit(e: React.MouseEvent<HTMLButtonElement, MouseEvent>) {
        showError(null);

        if (!dept || !city || !date || !title || !content) {
            showError("Please fill all required inputs");
        } else if (title.length > 100 || title.length < 10) {
            showError("Title length must be between 10 and 100 charecters");
        } else if (content.length < 200) {
            showError("Report must be atleast 200 charecters long");
        } else if (city.length < 5 || city.length > 50) {
            showError("City name length must be between 5 and 50");
        } else if (dept.length < 5 || dept.length > 50) {
            showError("Department name length must be between 5 and 50");
        } else {
            let r : ReportBuilder = {
                title,
                city: city[0],
                dept: dept[0],
                info: content,
                accountable: accountable?.id || null,
                created_at: date
            };

            let { error } = await supabase.from("reports").insert(r);
            if (error) {
                showError("Failed to add report, try again later");
            }
        }
    }

    return (
        <main className="p-2 py-8 max-w-xl mx-auto">
            <Head>
                <title> Scorpio | Write Report </title>
            </Head>

            <h1 className="flex items-center gap-2 text-2xl font-semibold">
                <Image alt="write icon" width={30} height={30} src="/write.png" />
                Write
            </h1>

            <form className="px-4 mt-4 flex flex-col gap-4 *:flex *:flex-col *:gap-1" onSubmit={e => e.preventDefault()}>
                <div className="sm:grid sm:grid-cols-2 sm:gap-4">
                    <Search
                        label="Department"
                        data={deptsArr}
                        display={s => s}
                        selected={dept}
                        setSelected={setDept}
                        debounce={false}
                        custom={s => s}
                        isSingle={true}
                    />

                    <Search
                        label="City"
                        data={citiesArr}
                        display={s => s}
                        selected={city}
                        setSelected={setCity}
                        debounce={false}
                        custom={s => s}
                        isSingle={true}
                    />
                </div>

                <fieldset>
                    <label>
                        Date
                    </label>

                    <input
                        className="p-2 bg-fuchsia-200 bg-opacity-10 w-fit"
                        onChange={(e) => setDate(e.target.value)}
                        type="date"
                        style={{"colorScheme": "dark"}}
                        placeholder="Date of Incidence"
                    />
                </fieldset>

                <fieldset>
                    <label>
                        Title
                    </label>

                    <input
                        className="p-2 bg-fuchsia-200 bg-opacity-10"
                        type="text"
                        placeholder="enter suitable title"
                        onChange={e => setTitle(e.target.value)}
                    />
                </fieldset>

                <fieldset>
                    <label>
                        Report
                    </label>

                    <textarea
                        className="p-2 min-h-52 bg-fuchsia-200 bg-opacity-10 resize-y"
                        onChange={(e) => setContent(e.target.value)}
                        placeholder="type your report"
                    />
                </fieldset>

                <SearchAsync
                    label="Profiles"
                    getData={getData}
                    selected={accountable}
                    setSelected={setAccountable}
                    display={item => item.name}
                />

                <button className="p-2 w-fit mx-auto bg-fuchsia-700 border-2 border-solid border-transparent hover:border-fuchsia-400" onClick={handleSubmit} type="submit">
                    Submit
                </button>

                {error && (
                    <p className="bad toast">
                        {error}
                    </p>
                )}
            </form>
        </main>
    );
}

// src/routes/write/+page.svelte
<script>
    import { cities, departments, showToast } from "$lib/utils";
    import SearchStatic from "$lib/components/SearchStatic.svelte";
    import SearchAsync from "$lib/components/SearchAsync.svelte";
    import supabase from "$lib/supabase";

    let /**@type {string}*/ title,
        /**@type {string}*/ info,
        /**@type {string}*/ date,
        /**@type {string|null}*/ city = null,
        /**@type {string|null}*/ dept = null,
        /**@type {ProfileSchema|null}*/ pf = null;

    async function addPost() {
        if (dept) dept = dept.trim();
        if (city) city = city.trim();

        if (!(title && dept && city && date && info)) {
            showToast("Please fill all required inputs");
        } else if (info.length < 200 || info.length > 4000) {
            showToast("Description has to be between 200 and 4000 charecters long");
        } else if (title.length < 20 || title.length > 200) {
            showToast("Title has to be between 20 and 200 charecters long");
        } else {
            /**@type {AddReport}*/
            let r = {
                timestamp: new Date(date),
                dept: dept,
                city: city,
                title,
                info, //TODO: sanitize input
                accountable: pf?.id || null,
            };

            let d = await supabase.from("reports").insert(r);

            d.error
                ? [console.error(d.error), showToast("Failed to submit report")]
                : showToast("Report submitted. Thank you.", "good");
        }
    }

    /**
     * @param {string} q
     * @returns {Promise<ProfileSchema[]>}
     */
    function getProfiles(q = "") {
        q = q.trim();

        return new Promise(async (res, rej) => {
            if (!q) return res([]);

            let d = await supabase
                .from("profiles")
                .select()
                .ilike("name", `%${q}%`)
                .limit(15);

            console.log("Matches:", d);

            if (d.error) rej(d.error);
            else res(d.data);
        });
    }
</script>

<svelte:head>
    <title>Scorpio | Write a Report</title>
</svelte:head>

<main>
    <form on:submit|preventDefault>
        <div class="title">
            <img src="/write.png" alt="write" width="30" height="30" />
            <h4>Write a Report</h4>
        </div>

        <div class="grid-2">
            <SearchStatic
                label="Department"
                data={departments}
                bind:value={dept}
            />
            <SearchStatic label="City" data={cities} bind:value={city} />
        </div>

        <fieldset>
            <label for="date"> Date: </label>
            <input
                name="date"
                bind:value={date}
                type="date"
                placeholder="Date"
            />
        </fieldset>

        <fieldset>
            <label for="title"> Title: </label>
            <input
                name="title"
                type="text"
                placeholder="write a suitable title"
                bind:value={title}
            />
        </fieldset>

        <fieldset>
            <label for="description"> Description: </label>

            <textarea
                name="description"
                placeholder="Elaborate on the incident - Mention - Name & Designation of Official and Location, Time, Date and Place of incidence."
                style="resize: vertical;"
                bind:value={info}
            ></textarea>
        </fieldset>

        <div class="pfBox">
            <SearchAsync
                label="Accountable person"
                getData={getProfiles}
                bind:value={pf}
            />
            <small style="opacity: .7"> (optional) </small>
        </div>

        <button type="submit" on:click={addPost}> Submit Report </button>
    </form>
</main>

<style>
    main {
        padding: 2rem;
    }

    form {
        margin-top: 2rem;
        max-width: 40rem;
        margin: 0 auto;
    }

    form > * {
        margin-top: 1rem;
        display: flex;
        flex-direction: column;
        position: relative;
    }

    form .grid-2 {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 2rem;
    }
    @media (max-width: 556px) {
        form .grid-2 {
            margin-top: 2rem;
            grid-template-columns: 1fr;
        }
    }

    .title {
        flex-direction: row;
        align-items: center;
    }

    form label {
        opacity: 0.8;
        margin-bottom: 0.2rem;
    }

    form textarea {
        min-height: 10rem;
    }

    fieldset input,
    fieldset textarea {
        font-size: 0.9rem;
    }

    form button[type="submit"] {
        margin: 0 auto;
        margin-top: 1rem;
    }

    input[type="date"] {
        width: fit-content;
    }
    input[type="date"]::-webkit-calendar-picker-indicator {
        cursor: pointer;
    }

    div.pfBox {
        margin-top: 1rem;
    }
</style>
