// src/lib/components/Report.svelte
<script>
    import { formatTimestamp } from "$lib/utils";
    import Profile from "$lib/components/Profile.svelte";

    export let /**@type {ReportSchema}*/ data,
        /**@type {boolean}*/ showMin = false,
        /**@type {boolean}*/ elevate = false;

    let r = data;
    
    /**
     * @param {string} s
     * @returns {string}
     */
    function formatInfo(s) {
        return s
            .replaceAll("\n", "<br/>")
            .replaceAll(/\*\*(.+?)\*\*/g, "<strong> $1 </strong>") //bold
            .replaceAll(/\_(.+?)\_/g, "<underline> $1 </underline>") //underline
            .replaceAll(/\*(.+?)\*/g, "<i> $1 </i>"); //italics
    }
</script>

<div class="report" class:elevate={elevate}>
    <span style="font-size: 1.2rem; font-weight: 600;"> {r.title} </span>

    <div class="details">
        <span> {formatTimestamp(r.created_at)} </span>
        <span> {r.dept} </span>
        <span> {r.city} </span>
    </div>

    <p>
        {#if showMin}
            {r.info.slice(0, 200)}
            {#if r.info.length > 200}
                <small style="opacity: .7;"> (read more) </small>
            {/if}
        {:else}
            <!--TODO: Sanitize input-->
            {@html formatInfo(r.info)}
        {/if}
    </p>

    {#if !showMin && r.accountable}
        <p>
            <span>Accountable person:</span>
            <a href="/profiles/{r.accountable.id}">
                <Profile data={r.accountable} showMin elevate />
            </a>
        </p>
    {/if}
</div>

<style>
    .report {
        padding: 1rem;
        max-width: 52rem;
        margin: 0 auto;
    }

    .report.elevate {
        border: 2px solid var(--elevate);
        background-color: var(--elevate);
    }

    .report .details {
        display: flex;
        flex-wrap: wrap;
        margin-top: 0.5rem;
    }

    .report .details > * {
        padding: 0 0.5rem;
        border-right: 2px solid var(--txt);
        font-size: 0.9rem;
        opacity: 0.9;
    }
    .report .details > *:last-child {
        border-right: none;
    }

    .report p {
        margin-top: 0.5rem;
        padding-top: 1rem;
        border-top: 1px solid var(--elevate);
    }
</style>

// app/components/Report.tsx
import Link from "next/link";
import { formatTimestamp } from "../lib/utils";
import Profile from "./Profile";

function Content({
    record,
    expand
}: {
    record: ReportSchema,
    expand: boolean
}
) {
    return (
        <div className="p-2">
            <h3 className="text-xl font-semibold">
                {record.title}
            </h3>

            <div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-sm *:px-2 *:bg-fuchsia-300 *:bg-opacity-10 *:text-fuchsia-400 *:text-nowrap">
                <span> {formatTimestamp(record.created_at)} </span>
                <span> {record.dept} </span>
                <span> {record.city} </span>
            </div>


            {expand
                ? (
                    // TODO: Sanitise
                    <p className="mt-3" dangerouslySetInnerHTML={{ __html: formatInfo(record.info)}} />
                ) : (
                    <p className="mt-3">
                        {record.info.slice(0, 200) + "..."}
                    </p>
                )
            }

            {expand && record.accountable && (
                <div className="mt-8">
                    <h4 className="text-sm text-fuchsia-300">
                        Accountable:
                    </h4>
                    
                    <Profile record={record.accountable} expand={false} />
                </div>
            )}
        </div>
    );
}

export default function Report({
    record,
    expand
}: {
    record: ReportSchema,
    expand: boolean
}) {
    let c = <Content record={record} expand={expand} />;

    if (expand) return c;

    return (
        <Link href={`/reports/${record.id}`} className="hover:bg-fuchsia-200 hover:bg-opacity-10">
            {c}
        </Link>
    );
}

function formatInfo(s: string) {
    //TODO: switch to markdown
    return s
        .replaceAll("\n", "<br/>")
        .replaceAll(/\*\*(.+?)\*\*/g, "<strong> $1 </strong>") //bold
        .replaceAll(/\_(.+?)\_/g, "<underline> $1 </underline>") //underline
        .replaceAll(/\*(.+?)\*/g, "<i> $1 </i>"); //italics
}
