// app/components/SearchAsync.tsx
import { Dispatch, SetStateAction, useEffect, useState } from "react";
import SearchInput from "./SearchInput";
import { PostgrestError, PostgrestSingleResponse } from "@supabase/supabase-js";
import Loading from "./Loading";
import "./search.css";

export default function SearchAsync<T>({
    label,
    getData,
    display,
    selected,
    setSelected
}: {
    label: string,
    getData: (q: string) => Promise<PostgrestSingleResponse<T[]>>,
    display: (item: T) => string,
    selected: T | null,
    setSelected: Dispatch<SetStateAction<T | null>>
}) {
    let [query, setQuery] = useState<string>("");
    let [data, setData] = useState<T[]>([]);
    let [loading, setLoading] = useState<boolean>(false);
    let [error, setError] = useState<PostgrestError | null>(null);

    useEffect(() => {
        if (query.trim().length === 0) return setData([]);

        setLoading(true);
        getData(query).then(({ data, error }) => {
            setError(error);
            error && console.error(error);
            setData(data || []);
            setLoading(false);
        });
    }, [query]);

    return (
        <fieldset className="search">
            <label>
                Tag Accountable person
            </label>

            <div className="selected">
                {selected && (
                    <button onClick={() => setSelected(null)}>
                        {display(selected)}
                        <span>x</span>
                    </button>
                )}
            </div>

            <div>
                <SearchInput
                    placeholder={"Type to find " + label}
                    setQuery={setQuery}
                    debounce={true}
                />

                <ul className="list">
                    {loading
                        ? <Loading />
                        : error
                        ? "Failed to load " + label
                        : query.trim().length === 0
                        ? "Type to search"
                        : data.length === 0
                        ? "No " + label + " found"
                        : data.map((item, idx) => (
                            <li className="show" key={idx}>
                                <button onClick={() => setSelected(item)}>
                                    {display(item)}
                                </button>
                            </li>
                        ))
                    }
                </ul>
            </div>

        </fieldset>
    );
}

// src/lib/components/SearchAsync.svelte
<script>
    import SearchInput from "$lib/components/SearchInput.svelte";
    import Loading from "./Loading.svelte";

    export let /**@type {function} returns Promise<any[]>**/ getData,
        /**@type {any|null} selected value of any[]*/ value,
        /**@type {string}*/ label;

    /**@type {Promise<any[]>}*/
    let data = new Promise(() => null);

    let query = "";

    $: {
        query;
        data = getData(query);
    }

    const display = (/** @type {any} */ item) => item.name;
</script>

<fieldset class="search">
    <label for={label}>
        {label}

        {#if value}
            <button class="minimal remove" on:click={() => (value = null)}>
                {display(value)} <span>x</span>
            </button>
        {/if}
    </label>

    <SearchInput {label} bind:query />

    <ul>
        {#await data}
            <Loading {label} />
        {:then data}
            {#if data.length === 0}
                <li> No {label} found </li>
            {/if}

            {#each data as item}
                <li class="show">
                    <button on:click={() => (value = item)}>
                        {display(item)}
                    </button>
                </li>
            {/each}
        {:catch error}
            Failed to find {label}: {error.message || error}
        {/await}
    </ul>
</fieldset>
